### ISSUE TITLE
On Demand URL Example?

### ISSUE THREAD

**Issue by jagthedrummer** [jkeen/ember-stereo#20]
This page seems to show an example of using an on demand url but the code snippet for the example is missing. It would be helpful to see the code, or to have an explanation of how it works.

https://ember-stereo.com/docs/playing-sounds#on-demand-url

**Comment by jkeen** [comment]
The code is the same as the example above it.

And "on demand" is WNYC radio lingo for just a static file, and maybe that should be changed… Just saying that that example is nothing fancy, it's just using a path to an mp3 file for the @identifier value you see in the code sample above it.

**Comment by jagthedrummer** [comment]
Ah! I was misunderstanding what on-demand meant in this context. I thought that it meant something like "after you click the play button we'll retrieve the actual URL over the network and then start to play it". (In my case the files are in a protected S3 bucket and I need to sign a request in order to be able to download them, and I incorrectly assumed that "on-demand" was for that kind of thing.)

**Comment by jkeen** [comment]
One thing that might not be very clear either is that you can pass a promise that returns an identifier (a url or an array of urls to try) into stereo to play, and it will resolve as part of the playing process. In your case that promise would return a signed url with a short expiration time, probably.

It was something that was built in a long ago to get past some some browser autoplay restrictions when the URL wasn't known at page load and it should still work! I haven't used that method lately for the projects that I use stereo on, but it sounds like it might be useful in your case.
