### ISSUE TITLE
Any plans to handle recording?

### ISSUE THREAD

**Issue by Techn1x** [jkeen/ember-stereo#5]
The most difficulty I've had with audio tends to be with recording it rather than playback, especially when trying to support all major browsers.

Is this something that might be part of future plans for ember-stereo?

**Comment by jkeen** [comment]
Not at this time, no. I hadn't even considered recording until your comment, here, and it does sound like an interesting problem to solve. I'm curious, what are the really tricky bits? 

The stuff that's on my lil' roadmap are all playback related: 

- out of the box player components
- allowing plug-in visualizations 
- cross-tab communication
- HLS improvements
